Update segment.py
Changed dict[] into Dict[] which is compatible with the latest version of Python 3.
dict[] gives an error : 
TypeError: 'type' object is not subscriptable